import 'dotenv/config';
import mongoose from 'mongoose';
import { connectDatabase, disconnectDatabase } from './config/database';
import { User } from './models/User';
import { Worker } from './models/Worker';
import { Employer } from './models/Employer';
import { Job } from './models/Job';

async function seed() {
  try {
    console.log('Connecting to database...');
    await connectDatabase();

    const workerPhone = `+9199999${Math.floor(10000 + Math.random() * 90000)}`;
    const employerPhone = `+9188888${Math.floor(10000 + Math.random() * 90000)}`;

    console.log(`Creating Worker User with phone: ${workerPhone}`);
    const workerUser = new User({
      phone_number: workerPhone,
      firebase_uid: `test_worker_uid_${Date.now()}`,
      has_worker: true,
      has_employer: false,
      active_role: 'worker',
      notification_permission: 'GRANTED',
    });
    await workerUser.save();

    console.log(`Creating Employer User with phone: ${employerPhone}`);
    const employerUser = new User({
      phone_number: employerPhone,
      firebase_uid: `test_employer_uid_${Date.now()}`,
      has_worker: false,
      has_employer: true,
      active_role: 'employer',
      notification_permission: 'GRANTED',
    });
    await employerUser.save();

    console.log('Creating Worker Profile...');
    const workerProfile = new Worker({
      user_id: workerUser._id,
      full_name: 'Test Worker',
      gender: 'Male',
      primary_skill: 'Chef',
      state_of_origin: 'Delhi',
      years_experience: 5,
      trust_score: 80,
      status: 'ACTIVE',
      home_location: {
        type: 'Point',
        coordinates: [78.563583, 17.365361],
      },
    });
    await workerProfile.save();

    console.log('Creating Employer Profile...');
    const employerProfile = new Employer({
      user_id: employerUser._id,
      property_name: 'Test Restaurant',
      property_type: 'Restaurant',
      contact_name: 'Test Owner',
      contact_phone: employerPhone,
      location: {
        type: 'Point',
        coordinates: [78.563583, 17.365361],
      },
      plan: 'PRO',
    });
    await employerProfile.save();

    const now = new Date();
    const centerLng = 78.4754325;
    const centerLat = 17.4432856;

    // --- Lane 1: Flash (⚡ 0-6h) ---
    // expires_at = shift_start_time + 30 min (per deriveLaneExpiry)
    // PER_SHIFT pay, urgent fill, shift_start_time set 1.5-5h from now

    const l1Shifts = [
      new Date(now.getTime() + 1.5 * 60 * 60 * 1000),
      new Date(now.getTime() + 2   * 60 * 60 * 1000),
      new Date(now.getTime() + 2.5 * 60 * 60 * 1000),
      new Date(now.getTime() + 3   * 60 * 60 * 1000),
      new Date(now.getTime() + 4   * 60 * 60 * 1000),
    ];

    const lane1Jobs = [
      {
        employer_id: employerProfile._id,
        lane: 1,
        job_title: 'Tandoor Cook - Urgent Cover',
        job_description: 'Urgent requirement for an experienced Tandoor Cook to cover a shift starting today. Must be proficient with naan, roti, and kebab preparations. Immediate start required.',
        primary_skill: 'cook',
        secondary_skills_preferred: ['Tandoor', 'North Indian'],
        cuisine_preferred: ['North Indian', 'Mughlai'],
        pay_type: 'PER_SHIFT',
        pay_rate: 900,
        number_of_openings: 1,
        openings_filled: 0,
        experience_years_min: 2,
        shift_start_time: l1Shifts[0],
        shift_end_time: new Date(l1Shifts[0].getTime() + 8 * 60 * 60 * 1000),
        shift_duration_hours: 8,
        expires_at: new Date(l1Shifts[0].getTime() + 30 * 60 * 1000),
        status: 'BROADCASTING',
        meals_provided: true,
        uniform_required: 'Chef whites and apron provided',
        geofence_radius_m: 15000,
        location: { type: 'Point', coordinates: [centerLng, centerLat] },
        keywords_extracted: ['tandoor', 'cook', 'urgent', 'north indian'],
      },
      {
        employer_id: employerProfile._id,
        lane: 1,
        job_title: 'Banquet Waiter - Evening Event',
        job_description: 'Need experienced banquet waiters for a large corporate dinner event tonight. Duties include table setup, food service, and guest interaction. Smart appearance mandatory.',
        primary_skill: 'waiter',
        secondary_skills_preferred: ['Banquet service', 'Fine dining protocol'],
        cuisine_preferred: [],
        pay_type: 'PER_SHIFT',
        pay_rate: 700,
        number_of_openings: 3,
        openings_filled: 1,
        experience_years_min: 1,
        shift_start_time: l1Shifts[1],
        shift_end_time: new Date(l1Shifts[1].getTime() + 6 * 60 * 60 * 1000),
        shift_duration_hours: 6,
        expires_at: new Date(l1Shifts[1].getTime() + 30 * 60 * 1000),
        status: 'PARTIALLY_FILLED',
        meals_provided: true,
        uniform_required: 'Black formal attire - provided on site',
        geofence_radius_m: 20000,
        location: { type: 'Point', coordinates: [centerLng + 0.02, centerLat + 0.01] },
        keywords_extracted: ['waiter', 'banquet', 'event', 'server'],
      },
      {
        employer_id: employerProfile._id,
        lane: 1,
        job_title: 'Barista - Morning Rush Cover',
        job_description: 'Staff shortage at our busy cafe. Looking for an experienced barista to handle the morning rush. Must be skilled in espresso, cappuccino, and cold brews. Latte art a plus.',
        primary_skill: 'barista',
        secondary_skills_preferred: ['Espresso', 'Latte art', 'Cold brew'],
        cuisine_preferred: ['Cafe', 'Beverages'],
        pay_type: 'PER_SHIFT',
        pay_rate: 750,
        number_of_openings: 1,
        openings_filled: 0,
        experience_years_min: 1,
        shift_start_time: l1Shifts[2],
        shift_end_time: new Date(l1Shifts[2].getTime() + 6 * 60 * 60 * 1000),
        shift_duration_hours: 6,
        expires_at: new Date(l1Shifts[2].getTime() + 30 * 60 * 1000),
        status: 'BROADCASTING',
        meals_provided: true,
        geofence_radius_m: 12000,
        special_instructions: 'Bring valid ID. Report directly to shift supervisor at counter.',
        location: { type: 'Point', coordinates: [centerLng - 0.03, centerLat + 0.02] },
        keywords_extracted: ['barista', 'coffee', 'cafe', 'espresso'],
      },
      {
        employer_id: employerProfile._id,
        lane: 1,
        job_title: 'Kitchen Helper / Dishwasher - Immediate',
        job_description: 'Immediate opening for a kitchen helper to assist with dish washing, vegetable prep, and general kitchen hygiene. No prior experience required. Fast learners welcome.',
        primary_skill: 'kitchen_helper',
        secondary_skills_preferred: ['Vegetable prep', 'Cleaning'],
        cuisine_preferred: [],
        pay_type: 'PER_SHIFT',
        pay_rate: 450,
        number_of_openings: 2,
        openings_filled: 0,
        experience_years_min: 0,
        shift_start_time: l1Shifts[3],
        shift_end_time: new Date(l1Shifts[3].getTime() + 8 * 60 * 60 * 1000),
        shift_duration_hours: 8,
        expires_at: new Date(l1Shifts[3].getTime() + 30 * 60 * 1000),
        status: 'BROADCASTING',
        meals_provided: true,
        geofence_radius_m: 10000,
        location: { type: 'Point', coordinates: [centerLng + 0.01, centerLat - 0.02] },
        keywords_extracted: ['kitchen helper', 'dishwasher', 'cleaning', 'helper'],
      },
      {
        employer_id: employerProfile._id,
        lane: 1,
        job_title: 'Cashier / POS Operator - Urgent',
        job_description: 'Cashier needed urgently for busy QSR outlet. Must be familiar with POS billing software, cash handling, and customer-facing service. Quick and accurate billing essential.',
        primary_skill: 'cashier',
        secondary_skills_preferred: ['POS billing', 'Cash handling', 'Customer service'],
        cuisine_preferred: [],
        pay_type: 'PER_SHIFT',
        pay_rate: 600,
        number_of_openings: 1,
        openings_filled: 0,
        experience_years_min: 1,
        shift_start_time: l1Shifts[4],
        shift_end_time: new Date(l1Shifts[4].getTime() + 8 * 60 * 60 * 1000),
        shift_duration_hours: 8,
        expires_at: new Date(l1Shifts[4].getTime() + 30 * 60 * 1000),
        status: 'BROADCASTING',
        meals_provided: true,
        geofence_radius_m: 10000,
        killer_questions: [
          { question: 'Have you used a POS billing system before?', answer_type: 'YES_NO', required: true },
        ],
        location: { type: 'Point', coordinates: [centerLng - 0.015, centerLat - 0.01] },
        keywords_extracted: ['cashier', 'POS', 'billing', 'cash handling'],
      },
    ];

    // --- Lane 2: Same-Day (🌅 6-24h) ---
    // expires_at = shift_start_time (per deriveLaneExpiry)
    // PER_SHIFT or DAILY pay, shift_start_time set 8-20h from now

    const l2Shifts = [
      new Date(now.getTime() + 8  * 60 * 60 * 1000),
      new Date(now.getTime() + 10 * 60 * 60 * 1000),
      new Date(now.getTime() + 12 * 60 * 60 * 1000),
      new Date(now.getTime() + 14 * 60 * 60 * 1000),
      new Date(now.getTime() + 18 * 60 * 60 * 1000),
    ];

    const lane2Jobs = [
      {
        employer_id: employerProfile._id,
        lane: 2,
        job_title: 'Line Cook - Continental Section',
        job_description: 'Skilled Line Cook needed for the Continental section of our multi-cuisine restaurant. Handle pasta, grills, and salads. Must maintain station hygiene and deliver during peak hours.',
        primary_skill: 'cook',
        secondary_skills_preferred: ['Pasta', 'Grilling', 'Plating'],
        cuisine_preferred: ['Continental', 'Italian', 'Mediterranean'],
        pay_type: 'PER_SHIFT',
        pay_min: 700,
        pay_max: 950,
        number_of_openings: 2,
        openings_filled: 0,
        experience_years_min: 2,
        shift_start_time: l2Shifts[0],
        shift_end_time: new Date(l2Shifts[0].getTime() + 8 * 60 * 60 * 1000),
        shift_duration_hours: 8,
        expires_at: l2Shifts[0],
        status: 'BROADCASTING',
        meals_provided: true,
        geofence_radius_m: 15000,
        location: { type: 'Point', coordinates: [centerLng + 0.04, centerLat + 0.02] },
        keywords_extracted: ['line cook', 'continental', 'pasta', 'grill'],
      },
      {
        employer_id: employerProfile._id,
        lane: 2,
        job_title: 'Delivery Rider - Food Delivery',
        job_description: 'Two-wheeler delivery riders needed for same-day coverage. Must have valid DL, own bike, and smartphone. Familiarity with Hyderabad roads and Google Maps navigation required.',
        primary_skill: 'delivery_rider',
        secondary_skills_preferred: ['Navigation', 'Customer handling'],
        cuisine_preferred: [],
        pay_type: 'DAILY',
        pay_min: 800,
        pay_max: 1200,
        number_of_openings: 3,
        openings_filled: 1,
        experience_years_min: 0,
        shift_start_time: l2Shifts[1],
        shift_end_time: new Date(l2Shifts[1].getTime() + 8 * 60 * 60 * 1000),
        shift_duration_hours: 8,
        expires_at: l2Shifts[1],
        status: 'PARTIALLY_FILLED',
        geofence_radius_m: 25000,
        special_instructions: 'Must have two-wheeler, valid DL, and Aadhaar ID on first day.',
        killer_questions: [
          { question: 'Do you own a two-wheeler with valid license?', answer_type: 'YES_NO', required: true },
          { question: 'Are you familiar with Hyderabad roads?', answer_type: 'YES_NO', required: false },
        ],
        location: { type: 'Point', coordinates: [centerLng - 0.02, centerLat + 0.03] },
        keywords_extracted: ['delivery', 'rider', 'two-wheeler', 'food delivery'],
      },
      {
        employer_id: employerProfile._id,
        lane: 2,
        job_title: 'Security Guard - Evening Shift',
        job_description: 'Security guard required for evening and night shift at a restaurant-hotel property. Duties include access control, CCTV monitoring, patrolling, and incident reporting.',
        primary_skill: 'security_guard',
        secondary_skills_preferred: ['CCTV monitoring', 'Access control', 'Incident reporting'],
        cuisine_preferred: [],
        pay_type: 'PER_SHIFT',
        pay_rate: 650,
        number_of_openings: 2,
        openings_filled: 0,
        experience_years_min: 1,
        shift_start_time: l2Shifts[2],
        shift_end_time: new Date(l2Shifts[2].getTime() + 10 * 60 * 60 * 1000),
        shift_duration_hours: 10,
        expires_at: l2Shifts[2],
        status: 'BROADCASTING',
        geofence_radius_m: 15000,
        minimum_qualification: 'Class 10 pass',
        location: { type: 'Point', coordinates: [centerLng + 0.06, centerLat - 0.03] },
        keywords_extracted: ['security', 'guard', 'CCTV', 'night shift'],
      },
      {
        employer_id: employerProfile._id,
        lane: 2,
        job_title: 'Housekeeping Staff - Hotel',
        job_description: 'Housekeeping staff needed for same-day coverage at a 3-star hotel. Responsibilities include room cleaning, linen change, bathroom sanitization, and turndown service.',
        primary_skill: 'housekeeping',
        secondary_skills_preferred: ['Room cleaning', 'Linen management', 'Guest interaction'],
        cuisine_preferred: [],
        pay_type: 'DAILY',
        pay_min: 650,
        pay_max: 850,
        number_of_openings: 4,
        openings_filled: 2,
        experience_years_min: 1,
        shift_start_time: l2Shifts[3],
        shift_end_time: new Date(l2Shifts[3].getTime() + 8 * 60 * 60 * 1000),
        shift_duration_hours: 8,
        expires_at: l2Shifts[3],
        status: 'PARTIALLY_FILLED',
        meals_provided: true,
        uniform_required: 'Hotel uniform provided on site',
        geofence_radius_m: 10000,
        location: { type: 'Point', coordinates: [centerLng - 0.04, centerLat - 0.02] },
        keywords_extracted: ['housekeeping', 'hotel', 'cleaning', 'room service'],
      },
      {
        employer_id: employerProfile._id,
        lane: 2,
        job_title: 'Steward - Banquet & Room Service',
        job_description: 'Experienced stewards needed for banquet and room service operations at our property tonight. Must be well-groomed, courteous, and efficient in food and beverage service.',
        primary_skill: 'steward',
        secondary_skills_preferred: ['Banquet setup', 'Room service', 'F&B service'],
        cuisine_preferred: [],
        pay_type: 'PER_SHIFT',
        pay_rate: 680,
        number_of_openings: 5,
        openings_filled: 2,
        experience_years_min: 1,
        shift_start_time: l2Shifts[4],
        shift_end_time: new Date(l2Shifts[4].getTime() + 7 * 60 * 60 * 1000),
        shift_duration_hours: 7,
        expires_at: l2Shifts[4],
        status: 'PARTIALLY_FILLED',
        meals_provided: true,
        uniform_required: 'Formal whites or hotel livery - provided',
        geofence_radius_m: 20000,
        location: { type: 'Point', coordinates: [centerLng + 0.03, centerLat + 0.05] },
        keywords_extracted: ['steward', 'banquet', 'room service', 'F&B'],
      },
    ];

    // --- Lane 3: Contract (📋 short contract, expires +7 days) ---
    // Monthly pay, contract_start_date, contract_duration, notice_period_max_days

    const lane3Expiry = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);

    const lane3Jobs = [
      {
        employer_id: employerProfile._id,
        lane: 3,
        job_title: 'South Indian Chef - 3 Month Contract',
        job_description: 'Experienced South Indian Chef required for a 3-month contract at a premium breakfast and tiffin outlet. Must be proficient in dosas, idlis, vadas, and various chutneys. High consistency and speed essential.',
        primary_skill: 'cook',
        secondary_skills_preferred: ['Dosa preparation', 'Chutneys', 'Idli-vada'],
        cuisine_preferred: ['South Indian', 'Andhra'],
        pay_type: 'MONTHLY',
        pay_min: 20000,
        pay_max: 26000,
        number_of_openings: 2,
        openings_filled: 0,
        experience_years_min: 3,
        expires_at: lane3Expiry,
        contract_start_date: new Date(now.getTime() + 5 * 24 * 60 * 60 * 1000),
        contract_duration: '3 months',
        notice_period_max_days: 7,
        status: 'BROADCASTING',
        accommodation_provided: true,
        meals_provided: true,
        geofence_radius_m: 20000,
        location: { type: 'Point', coordinates: [centerLng + 0.05, centerLat + 0.03] },
        keywords_extracted: ['south indian', 'chef', 'dosa', 'contract'],
      },
      {
        employer_id: employerProfile._id,
        lane: 3,
        job_title: 'Electrician / Maintenance Technician - 6 Week Contract',
        job_description: 'Qualified electrician required for a 6-week maintenance contract at a large hotel property. Duties include preventive maintenance, fault diagnosis, panel work, and safety compliance checks.',
        primary_skill: 'electrician',
        secondary_skills_preferred: ['Preventive maintenance', 'Panel work', 'Safety compliance'],
        cuisine_preferred: [],
        pay_type: 'MONTHLY',
        pay_min: 22000,
        pay_max: 28000,
        number_of_openings: 1,
        openings_filled: 0,
        experience_years_min: 3,
        expires_at: lane3Expiry,
        contract_start_date: new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000),
        contract_duration: '6 weeks',
        notice_period_max_days: 5,
        minimum_qualification: 'ITI Electrician trade certificate',
        status: 'BROADCASTING',
        accommodation_provided: false,
        transport_provided: true,
        geofence_radius_m: 15000,
        location: { type: 'Point', coordinates: [centerLng - 0.05, centerLat + 0.04] },
        keywords_extracted: ['electrician', 'maintenance', 'ITI', 'hotel'],
      },
      {
        employer_id: employerProfile._id,
        lane: 3,
        job_title: 'Front Desk Receptionist - 2 Month Cover',
        job_description: 'Hotel receptionist needed to cover a 2-month maternity leave absence. Responsibilities include check-in/check-out, reservation management, guest queries, and coordinating with housekeeping and F&B.',
        primary_skill: 'receptionist',
        secondary_skills_preferred: ['Hotel PMS', 'Guest relations', 'Reservation management'],
        cuisine_preferred: [],
        pay_type: 'MONTHLY',
        pay_min: 18000,
        pay_max: 22000,
        number_of_openings: 1,
        openings_filled: 0,
        experience_years_min: 1,
        expires_at: lane3Expiry,
        contract_start_date: new Date(now.getTime() + 4 * 24 * 60 * 60 * 1000),
        contract_duration: '2 months',
        notice_period_max_days: 7,
        minimum_qualification: 'Hotel Management diploma or equivalent',
        status: 'BROADCASTING',
        geofence_radius_m: 15000,
        killer_questions: [
          { question: 'Are you familiar with any hotel PMS software (e.g. Opera, IDS)?', answer_type: 'YES_NO', required: true },
          { question: 'Can you speak English and Hindi?', answer_type: 'YES_NO', required: true },
        ],
        location: { type: 'Point', coordinates: [centerLng + 0.07, centerLat - 0.01] },
        keywords_extracted: ['receptionist', 'front desk', 'hotel', 'PMS'],
      },
      {
        employer_id: employerProfile._id,
        lane: 3,
        job_title: 'Bartender - Events Contract (8 Weeks)',
        job_description: 'Experienced bartender needed for an 8-week events and catering contract. Must be skilled in classic cocktails, mocktails, and bar hygiene. Weekend events and late shifts involved.',
        primary_skill: 'bartender',
        secondary_skills_preferred: ['Cocktails', 'Mocktails', 'Bar management'],
        cuisine_preferred: ['Beverages', 'Bar'],
        pay_type: 'MONTHLY',
        pay_min: 24000,
        pay_max: 30000,
        number_of_openings: 2,
        openings_filled: 0,
        experience_years_min: 2,
        expires_at: lane3Expiry,
        contract_start_date: new Date(now.getTime() + 6 * 24 * 60 * 60 * 1000),
        contract_duration: '8 weeks',
        notice_period_max_days: 7,
        status: 'BROADCASTING',
        meals_provided: true,
        transport_provided: true,
        geofence_radius_m: 20000,
        special_instructions: 'FSSAI food handler certificate preferred. Weekend availability mandatory.',
        location: { type: 'Point', coordinates: [centerLng - 0.06, centerLat + 0.06] },
        keywords_extracted: ['bartender', 'cocktails', 'bar', 'events'],
      },
      {
        employer_id: employerProfile._id,
        lane: 3,
        job_title: 'Sous Chef - Contract Kitchen Cover (10 Weeks)',
        job_description: 'Sous Chef needed on a 10-week contract to assist the Head Chef during peak season. Responsibilities include station management, mise en place supervision, recipe consistency, and junior staff training.',
        primary_skill: 'cook',
        secondary_skills_preferred: ['Station management', 'Mise en place', 'Team supervision'],
        cuisine_preferred: ['Multi-cuisine', 'Indian', 'Continental'],
        pay_type: 'MONTHLY',
        pay_min: 32000,
        pay_max: 40000,
        number_of_openings: 1,
        openings_filled: 0,
        experience_years_min: 5,
        expires_at: lane3Expiry,
        contract_start_date: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000),
        contract_duration: '10 weeks',
        notice_period_max_days: 10,
        minimum_qualification: 'Hotel Management degree or culinary arts diploma',
        status: 'BROADCASTING',
        accommodation_provided: true,
        meals_provided: true,
        transport_provided: false,
        cream_pool_first: true,
        geofence_radius_m: 25000,
        location: { type: 'Point', coordinates: [centerLng + 0.02, centerLat - 0.06] },
        keywords_extracted: ['sous chef', 'kitchen', 'contract', 'management'],
      },
    ];

    // --- Lane 4: Permanent (🏢 long-term, expires +30 days) ---
    // Monthly/Annual pay, interview_required, interview_format, contract_start_date

    const lane4Expiry = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);

    const lane4Jobs = [
      {
        employer_id: employerProfile._id,
        lane: 4,
        job_title: 'Head Chef - Fine Dining Restaurant',
        job_description: 'Seeking an accomplished Head Chef to lead our culinary team at a high-end fine dining restaurant. Responsible for full menu design, costing, quality control, vendor management, and kitchen brigade leadership. Must have proven track record in fine dining.',
        primary_skill: 'cook',
        secondary_skills_preferred: ['Menu planning', 'Team leadership', 'Food costing', 'Vendor management'],
        cuisine_preferred: ['Fusion', 'Modern Indian', 'French'],
        pay_type: 'MONTHLY',
        pay_min: 55000,
        pay_max: 75000,
        number_of_openings: 1,
        openings_filled: 0,
        experience_years_min: 8,
        expires_at: lane4Expiry,
        contract_start_date: new Date(now.getTime() + 21 * 24 * 60 * 60 * 1000),
        notice_period_max_days: 30,
        minimum_qualification: 'Hotel Management degree or equivalent culinary qualification',
        interview_required: true,
        interview_format: 'In-Person',
        status: 'BROADCASTING',
        accommodation_provided: true,
        meals_provided: true,
        transport_provided: false,
        cream_pool_first: true,
        boost_active: true,
        boost_count: 1,
        pay_vs_market: 15,
        geofence_radius_m: 30000,
        killer_questions: [
          { question: 'Have you led a kitchen team of more than 10 people?', answer_type: 'YES_NO', required: true },
          { question: 'Do you have experience designing seasonal menus?', answer_type: 'YES_NO', required: true },
        ],
        location: { type: 'Point', coordinates: [centerLng, centerLat - 0.12] },
        keywords_extracted: ['head chef', 'fine dining', 'menu design', 'leadership'],
      },
      {
        employer_id: employerProfile._id,
        lane: 4,
        job_title: 'Restaurant General Manager',
        job_description: 'Experienced General Manager needed to oversee all restaurant operations including F&B service, staffing, P&L management, customer experience, and regulatory compliance. Reports directly to ownership.',
        primary_skill: 'manager',
        secondary_skills_preferred: ['P&L management', 'Staff recruitment', 'Guest relations', 'Compliance'],
        cuisine_preferred: [],
        pay_type: 'MONTHLY',
        pay_min: 50000,
        pay_max: 70000,
        number_of_openings: 1,
        openings_filled: 0,
        experience_years_min: 7,
        expires_at: lane4Expiry,
        contract_start_date: new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000),
        notice_period_max_days: 30,
        minimum_qualification: 'MBA or Hotel Management degree',
        interview_required: true,
        interview_format: 'Both',
        status: 'BROADCASTING',
        transport_provided: true,
        meals_provided: true,
        cream_pool_first: true,
        boost_active: false,
        pay_vs_market: 10,
        geofence_radius_m: 40000,
        killer_questions: [
          { question: 'Have you managed a restaurant with revenue above 1 Cr/month?', answer_type: 'YES_NO', required: true },
          { question: 'How many years of F&B management experience do you have?', answer_type: 'TEXT', required: true },
          { question: 'Are you comfortable with a 6-day work week?', answer_type: 'YES_NO', required: true },
        ],
        location: { type: 'Point', coordinates: [centerLng - 0.08, centerLat + 0.1] },
        keywords_extracted: ['general manager', 'restaurant', 'P&L', 'operations'],
      },
      {
        employer_id: employerProfile._id,
        lane: 4,
        job_title: 'Housekeeping Supervisor - Hotel Property',
        job_description: 'Permanent Housekeeping Supervisor required to manage a team of 15-20 housekeeping staff at a 4-star hotel. Responsible for room quality standards, linen inventory, chemical consumption, and guest satisfaction scores.',
        primary_skill: 'housekeeping',
        secondary_skills_preferred: ['Team management', 'Linen inventory', 'Quality standards', 'Guest satisfaction'],
        cuisine_preferred: [],
        pay_type: 'MONTHLY',
        pay_min: 28000,
        pay_max: 36000,
        number_of_openings: 1,
        openings_filled: 0,
        experience_years_min: 5,
        expires_at: lane4Expiry,
        contract_start_date: new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000),
        notice_period_max_days: 30,
        minimum_qualification: 'Hotel Management diploma or 5 years supervisory experience',
        interview_required: true,
        interview_format: 'In-Person',
        status: 'BROADCASTING',
        accommodation_provided: true,
        meals_provided: true,
        geofence_radius_m: 20000,
        location: { type: 'Point', coordinates: [centerLng + 0.09, centerLat + 0.05] },
        keywords_extracted: ['housekeeping supervisor', 'hotel', 'team management', 'quality'],
      },
      {
        employer_id: employerProfile._id,
        lane: 4,
        job_title: 'Security Supervisor - Multi-Property',
        job_description: 'Head of Security needed to manage security operations across two restaurant-hotel properties. Oversee a team of 10 guards, coordinate with local authorities, conduct risk assessments, and maintain CCTV and access control systems.',
        primary_skill: 'security_guard',
        secondary_skills_preferred: ['CCTV management', 'Risk assessment', 'Team management', 'Incident reporting'],
        cuisine_preferred: [],
        pay_type: 'MONTHLY',
        pay_min: 32000,
        pay_max: 42000,
        number_of_openings: 1,
        openings_filled: 0,
        experience_years_min: 6,
        expires_at: lane4Expiry,
        contract_start_date: new Date(now.getTime() + 21 * 24 * 60 * 60 * 1000),
        notice_period_max_days: 30,
        minimum_qualification: 'Ex-military or police background preferred',
        interview_required: true,
        interview_format: 'In-Person',
        status: 'BROADCASTING',
        accommodation_provided: true,
        meals_provided: true,
        geofence_radius_m: 30000,
        special_instructions: 'Background verification mandatory. PSA/PSARA license preferred.',
        location: { type: 'Point', coordinates: [centerLng - 0.1, centerLat - 0.08] },
        keywords_extracted: ['security supervisor', 'CCTV', 'multi-property', 'team management'],
      },
      {
        employer_id: employerProfile._id,
        lane: 4,
        job_title: 'Accounts & Back Office Executive',
        job_description: 'Accounts executive needed to manage day-to-day bookkeeping, vendor payments, GST filing, payroll coordination, and monthly MIS reporting for a restaurant group with 3 outlets.',
        primary_skill: 'accountant',
        secondary_skills_preferred: ['Tally ERP', 'GST filing', 'Payroll', 'MIS reporting'],
        cuisine_preferred: [],
        pay_type: 'MONTHLY',
        pay_min: 25000,
        pay_max: 35000,
        number_of_openings: 1,
        openings_filled: 0,
        experience_years_min: 3,
        expires_at: lane4Expiry,
        contract_start_date: new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000),
        notice_period_max_days: 30,
        minimum_qualification: 'B.Com or equivalent accounting qualification',
        interview_required: true,
        interview_format: 'Video Call',
        status: 'BROADCASTING',
        geofence_radius_m: 25000,
        killer_questions: [
          { question: 'Are you proficient in Tally ERP?', answer_type: 'YES_NO', required: true },
          { question: 'Have you handled GST returns independently?', answer_type: 'YES_NO', required: true },
        ],
        location: { type: 'Point', coordinates: [centerLng + 0.04, centerLat + 0.09] },
        keywords_extracted: ['accounts', 'Tally', 'GST', 'bookkeeping', 'back office'],
      },
    ];

    const allJobs = [...lane1Jobs, ...lane2Jobs, ...lane3Jobs, ...lane4Jobs];

    for (const jobData of allJobs) {
      const job = new Job(jobData);
      await job.save();
      console.log(`Created Job [Lane ${job.lane}]: ${job.job_title}`);
    }

    console.log(`\nSeed complete. Created ${allJobs.length} jobs across 4 lanes.`);
    console.log('  Lane 1 (Flash):     5 jobs');
    console.log('  Lane 2 (Same-Day):  5 jobs');
    console.log('  Lane 3 (Contract):  5 jobs');
    console.log('  Lane 4 (Permanent): 5 jobs');

  } catch (error) {
    console.error('Error seeding data:', error);
  } finally {
    await disconnectDatabase();
    console.log('Disconnected from database.');
  }
}

seed();
